services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      - db
  
  web:
    build: .
    command: python princesse/manage.py runserver 0.0.0.0:8000 --settings=settings.local
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    stdin_open: true
    tty: true
    depends_on:
      - db
