# Generated by Django 4.2.10 on 2024-09-28 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.IntegerField(editable=False, primary_key=True, serialize=False, verbose_name='Payment ID')),
                ('small_amount_ok', models.BooleanField(default=False)),
                ('small_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Small amount')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total amount')),
                ('status', models.CharField(choices=[('NO RETIRADO', 'NO RETIRADO'), ('RETIRADO', 'RETIRADO'), ('VENCIDO', 'VENCIDO'), ('DEVUELTO', 'DEVUELTO')], default='NO RETIRADO', max_length=30, verbose_name='Payment Status')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Rental date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Return date')),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.clientpayer')),
                ('pantalones', models.ManyToManyField(blank=True, to='clothes.pantalon')),
                ('sacos', models.ManyToManyField(blank=True, to='clothes.saco')),
                ('trajes', models.ManyToManyField(blank=True, to='clothes.traje')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
