# Generated by Django 5.1.1 on 2024-10-27 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Payment ID')),
                ('small_amount_ok', models.BooleanField(default=False)),
                ('small_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Small amount')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total amount')),
                ('status', models.CharField(choices=[('NO RETIRADO', 'NO RETIRADO'), ('RETIRADO', 'RETIRADO'), ('VENCIDO', 'VENCIDO'), ('DEVUELTO', 'DEVUELTO')], default='NO RETIRADO', max_length=30, verbose_name='Payment Status')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Rental date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Return date')),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.clientpayer')),
                ('combo', models.ManyToManyField(blank=True, to='product.combo')),
                ('productos', models.ManyToManyField(blank=True, to='product.producto')),
            ],
        ),
    ]
