# Generated by Django 5.1.1 on 2024-12-11 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('product', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.clientpayer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='combo',
            field=models.ManyToManyField(blank=True, to='product.combo'),
        ),
        migrations.AddField(
            model_name='payment',
            name='productos',
            field=models.ManyToManyField(blank=True, to='product.producto'),
        ),
    ]
