# Generated by Django 5.1.5 on 2025-01-15 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('product', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.clientpayer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='combo',
            field=models.ManyToManyField(blank=True, to='product.combo'),
        ),
        migrations.AddField(
            model_name='payment',
            name='productos',
            field=models.ManyToManyField(blank=True, to='product.producto'),
        ),
        migrations.AddField(
            model_name='paymentcombo',
            name='combo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.combo'),
        ),
        migrations.AddField(
            model_name='paymentcombo',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.payment'),
        ),
        migrations.AddField(
            model_name='paymentproduct',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.payment'),
        ),
        migrations.AddField(
            model_name='paymentproduct',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.producto'),
        ),
    ]
