# Generated by Django 5.1.5 on 2025-02-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('product', '0003_customproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='custom_products',
            field=models.ManyToManyField(blank=True, related_name='payments', to='product.customproduct'),
        ),
    ]
