# Generated by Django 5.1.1 on 2024-12-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_client_payment_combo_payment_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='price_type',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('DEBITO', 'Débito'), ('CREDITO', 'Crédito')], default='EFECTIVO', max_length=10, verbose_name='Tipo de precio'),
        ),
    ]
