# Generated by Django 5.1.5 on 2025-03-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_paymentproduct_precio_credito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcombo',
            name='precio_credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentcombo',
            name='precio_debito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentcombo',
            name='precio_efectivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
