# Generated by Django 5.1.1 on 2024-12-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_price_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de recibo'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pick_up_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de retiro'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de devolución'),
        ),
    ]
