# Generated by Django 5.1.1 on 2024-12-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, choices=[('NO RETIRADO', 'NO RETIRADO'), ('RETIRADO', 'RETIRADO'), ('VENCIDO', 'VENCIDO'), ('PARCIAL', 'PARCIAL'), ('DEVUELTO', 'DEVUELTO')], default='NO RETIRADO', max_length=30, null=True, verbose_name='Estado'),
        ),
    ]
