# Generated by Django 5.1.5 on 2025-06-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_payment_custom_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('ALQUILER', 'ALQUILER'), ('VENTA', 'VENTA')], default='ALQUILER', max_length=10, verbose_name='Tipo de pago'),
        ),
        migrations.AddField(
            model_name='payment',
            name='test_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de prueba'),
        ),
    ]
