# Generated by Django 5.1.1 on 2025-01-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_paymentproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='price_type',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('debito', 'Débito'), ('credito', 'Crédito')], default='efectivo', max_length=10, verbose_name='Tipo de precio'),
        ),
    ]
