# Generated by Django 5.1.5 on 2025-07-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_payment_payment_type_payment_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='price_type',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('debito', 'Débito'), ('credito', 'Crédito'), ('dolares', 'Dolares')], default='efectivo', max_length=10, verbose_name='Tipo de precio'),
        ),
    ]
