# Generated by Django 5.1.1 on 2025-01-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_payment_price_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='descuento',
            field=models.IntegerField(default=0, verbose_name='Descuento'),
        ),
        migrations.AddField(
            model_name='payment',
            name='detail_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Detalle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal'),
            preserve_default=False,
        ),
    ]
