# Generated by Django 5.1.1 on 2025-01-14 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_payment_descuento_payment_detail_amount_and_more'),
        ('product', '0012_remove_combo_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.combo')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.payment')),
            ],
        ),
    ]
