# Generated by Django 4.2.10 on 2024-09-28 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('tipo_prenda', models.CharField(choices=[('general', 'General'), ('vestido', 'Vestido'), ('saco', 'Saco'), ('pantalon', 'Pantalon')], default='general', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pantalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DISPONIBLE', 'DISPONIBLE'), ('ALQUILADO', 'ALQUILADO')], default='DISPONIBLE', max_length=30, verbose_name='Clothes Status')),
                ('tipo', models.CharField(default='Pantalon', max_length=50)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.color')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clothes.marca')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Saco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DISPONIBLE', 'DISPONIBLE'), ('ALQUILADO', 'ALQUILADO')], default='DISPONIBLE', max_length=30, verbose_name='Clothes Status')),
                ('tipo', models.CharField(default='Saco', max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.color')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clothes.marca')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Talle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Traje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_traje', models.CharField(choices=[('Ambo', 'Ambo'), ('Smoking', 'Smoking')], max_length=50)),
                ('pantalon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.pantalon')),
                ('saco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.saco')),
            ],
        ),
        migrations.AddField(
            model_name='saco',
            name='talle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.talle'),
        ),
        migrations.AddField(
            model_name='saco',
            name='tela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clothes.tela'),
        ),
        migrations.AddField(
            model_name='pantalon',
            name='talle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.talle'),
        ),
        migrations.AddField(
            model_name='pantalon',
            name='tela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clothes.tela'),
        ),
    ]
