# Generated by Django 5.1.1 on 2024-10-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=50, verbose_name='DNI')),
                ('cuit', models.CharField(max_length=50, verbose_name='CUIT')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefono')),
                ('iva', models.CharField(choices=[('RESPONSABLEINSCRIPTO', 'RESPONSABLE INSCRIPTO'), ('NORESPONSABLE', 'NO RESPONSABLE'), ('MONOTRIBUTISTA', 'MONOTRIBUTISTA'), ('EXENTO', 'EXENTO'), ('CONSUMIDORFINAL', 'CONSUMIDOR FINAL')], default='RESPONSABLEINSCRIPTO', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client Payer',
                'verbose_name_plural': 'Clients Payer',
            },
        ),
    ]
