# Generated by Django 5.1.1 on 2025-01-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpayer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Direccion de email'),
        ),
    ]
