# Generated by Django 5.1.5 on 2025-01-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpayer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
