# Generated by Django 5.1.5 on 2025-05-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_clientpayer_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpayer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Direccion de email'),
        ),
    ]
