# Generated by Django 5.1.5 on 2025-06-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_clientpayer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpayer',
            name='dni',
            field=models.CharField(max_length=10, unique=True, verbose_name='DNI'),
        ),
    ]
