# Generated by Django 5.1.1 on 2025-01-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpayer',
            name='cuit',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='CUIT'),
        ),
        migrations.AlterField(
            model_name='clientpayer',
            name='iva',
            field=models.CharField(blank=True, choices=[('RESPONSABLE_INSCRIPTO', 'RESPONSABLE INSCRIPTO'), ('NO_RESPONSABLE', 'NO RESPONSABLE'), ('MONOTRIBUTISTA', 'MONOTRIBUTISTA'), ('EXENTO', 'EXENTO'), ('CONSUMIDOR_FINAL', 'CONSUMIDOR FINAL')], default='RESPONSABLE_INSCRIPTO', max_length=30, null=True),
        ),
    ]
