# Generated by Django 5.1.5 on 2025-01-20 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Talle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrecioCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Efectivo')),
                ('debito', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Débito')),
                ('credito', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Crédito')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.marca')),
            ],
            options={
                'unique_together': {('marca',)},
            },
        ),
        migrations.CreateModel(
            name='PrecioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Efectivo')),
                ('debito', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Débito')),
                ('credito', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Crédito')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.categoria')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.marca')),
            ],
            options={
                'unique_together': {('categoria', 'marca')},
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.categoria')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.color')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.marca')),
                ('precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='product.precioproducto')),
                ('talle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.talle')),
                ('tela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.tela')),
            ],
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.color')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.marca')),
                ('precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='product.preciocombo')),
                ('productos', models.ManyToManyField(blank=True, to='product.producto')),
                ('talle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.talle')),
            ],
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(condition=models.Q(('tela__isnull', False)), fields=('categoria', 'marca', 'color', 'talle', 'tela'), name='unique_producto'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(condition=models.Q(('tela__isnull', True)), fields=('categoria', 'marca', 'color', 'talle'), name='unique_producto_tela_null'),
        ),
    ]
