# Generated by Django 5.1.1 on 2024-11-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Credito'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_debito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Debito'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_efectivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Efectivo'),
        ),
    ]
