# Generated by Django 5.1.1 on 2024-12-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('categoria', 'marca', 'color', 'talle', 'tela'), name='unique_producto'),
        ),
    ]
