# Generated by Django 5.1.1 on 2024-12-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_producto_unique_producto'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='producto',
            name='unique_producto',
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(condition=models.Q(('tela__isnull', False)), fields=('categoria', 'marca', 'color', 'talle', 'tela'), name='unique_producto'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(condition=models.Q(('tela__isnull', True)), fields=('categoria', 'marca', 'color', 'talle'), name='unique_producto_tela_null'),
        ),
    ]
