# Generated by Django 5.1.5 on 2025-02-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_combo_active_producto_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Descripción')),
                ('color', models.CharField(max_length=100, verbose_name='Color')),
                ('talle', models.CharField(max_length=100, verbose_name='Talle')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio')),
                ('cantidad', models.PositiveIntegerField()),
            ],
        ),
    ]
