# Generated by Django 5.1.1 on 2025-01-03 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_producto_unique_producto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='precio',
            old_name='precio_credito',
            new_name='credito',
        ),
        migrations.RenameField(
            model_name='precio',
            old_name='precio_debito',
            new_name='debito',
        ),
        migrations.RenameField(
            model_name='precio',
            old_name='precio_efectivo',
            new_name='efectivo',
        ),
    ]
