# Generated by Django 5.1.5 on 2025-04-24 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_payment_custom_products_and_more'),
        ('product', '0003_customproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customproduct',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_products', to='payment.payment'),
        ),
    ]
