# Generated by Django 5.1.1 on 2025-01-09 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_precio_credito_precio_credito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='combo',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combo',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.marca'),
        ),
    ]
