# Generated by Django 5.1.5 on 2025-06-02 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_customproduct_is_active_customproduct_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.marca'),
            preserve_default=False,
        ),
    ]
