# Generated by Django 5.1.1 on 2025-01-10 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_combo_nombre_combo_categoria_combo_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='precio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='product.precio'),
            preserve_default=False,
        ),
    ]
