# Generated by Django 5.1.5 on 2025-06-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_combo_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='type',
            field=models.CharField(default='combo', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='type',
            field=models.CharField(default='producto', max_length=10, verbose_name='Tipo'),
        ),
    ]
