# Generated by Django 5.1.1 on 2025-01-10 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_combo_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Efectivo')),
                ('debito', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Débito')),
                ('credito', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Crédito')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.categoria')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.marca')),
            ],
            options={
                'abstract': False,
                'unique_together': {('categoria', 'marca')},
            },
        ),
        migrations.AlterField(
            model_name='combo',
            name='precio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='product.preciocombo'),
        ),
        migrations.CreateModel(
            name='PrecioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Efectivo')),
                ('debito', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Débito')),
                ('credito', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Crédito')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.categoria')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.marca')),
            ],
            options={
                'abstract': False,
                'unique_together': {('categoria', 'marca')},
            },
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='product.precioproducto'),
        ),
        migrations.DeleteModel(
            name='Precio',
        ),
    ]
