# Generated by Django 5.1.1 on 2025-01-10 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_preciocombo_alter_combo_precio_precioproducto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='categoria',
        ),
    ]
