# Generated by Django 5.1.1 on 2025-01-13 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_combo_categoria'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='preciocombo',
            unique_together={('marca',)},
        ),
        migrations.RemoveField(
            model_name='preciocombo',
            name='categoria',
        ),
    ]
