# Generated by Django 5.1.1 on 2025-01-13 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_preciocombo_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combo',
            name='talle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.talle'),
            preserve_default=False,
        ),
    ]
