# Generated by Django 5.1.1 on 2025-01-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_combo_color_combo_talle'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
