# Generated by Django 5.1.1 on 2025-01-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_combo_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='cantidad',
        ),
    ]
